FROM node:20-alpine

RUN apk add --no-cache git

RUN git clone https://github.com/duplaja/actual-simplefin-sync.git /opt/actual-simplefin-sync
WORKDIR /opt/actual-simplefin-sync

# Add custom crontab
COPY etc/crontab /etc/crontabs/root
RUN chown root:root /etc/crontabs/root && chmod 600 /etc/crontabs/root

# Add entrypoint
COPY bin/entrypoint /usr/local/bin/entrypoint
RUN chmod 700 /usr/local/bin/entrypoint

CMD ["entrypoint"]
